name: modifier_test
description: >-
  A testing helper package to optimize chain style programming in test.
  It's a peer of the modifier package.
version: 0.1.0
environment: {sdk: ">=3.4.3 <4.0.0", flutter: ">=3.22.0"}

dependencies:
  flutter: {sdk: flutter}

dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^3.0.0
