name: publish

on:
  push: {tags: ["[0-9]+.[0-9]+.[0-9]+*"]}

jobs:
  # https://dart.dev/tools/pub/automated-publishing
  publish:
    runs-on: ubuntu-latest
    permissions: {id-token: write}
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v3
      - uses: flutter-actions/setup-pubdev-credentials@v1
      - run: sh review.sh
      - run: dart pub publish --force
