name: review

on:
  push: {branches: ["main", "dev"]}
  pull_request: {branches: ["main", "dev"]}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v3
      - run: sh review.sh
